trigger:
  - main  # Trigger on your main branch (or whichever branch you prefer)

pool:
  name: 'aks-pool'  # Your self-hosted AKS pool

variables:
  registry: 'maizmazin/vproappazure'  # Docker registry name
  imageTag: 'V$(Build.BuildId)'        # Use build ID as image tag

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: |
              echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_17_X64)"
              echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_17_X64)/bin:$(PATH)"
            displayName: "Set Java 17 Version"

          - task: Maven@4
            inputs:
              azureSubscription: 'aks-service-conn'
              mavenPomFile: 'pom.xml'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
            displayName: 'Set up Maven'

          - script: mvn -v  # Verify Maven installation
            displayName: 'Verify Maven Installation'

          - script: mvn clean install -DskipTests
            displayName: 'Maven Clean Install'

          # Add a debug step to verify file paths
          - script: |
              ls -R $(Build.SourcesDirectory)/target
            displayName: 'Verify War File Generation'

          # Publish WAR file as an artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish WAR Artifact'
            inputs:
              pathToPublish: '$(Build.SourcesDirectory)/target/vprofile-v2.war'  # Adjusted path to the generated WAR file
              artifactName: 'war-files'

  - stage: BuildAndPushDockerImage
    jobs:
      - job: BuildAndPushDockerImage
        steps:
          # Download the WAR artifact from the previous build
          - task: DownloadBuildArtifacts@0
            displayName: 'Download WAR Artifact'
            inputs:
              buildType: 'current'  # Get the artifacts from the current build
              downloadType: 'single'
              artifactName: 'war-files'  # Name of the artifact to download
              downloadPath: '$(Build.SourcesDirectory)/target'  # Ensure WAR file is downloaded to the target directory

          # Build Docker image using the downloaded WAR file
          - script: |
              docker build -t $(registry):$(imageTag) -t $(registry):latest .
            displayName: 'Build Docker Image'

          # Push Docker image to the registry
          - script: |
              echo $(DOCKER_PASSWORD) | docker login --username $(DOCKER_USERNAME) --password-stdin
              docker push $(registry):$(imageTag)
              docker push $(registry):latest
            displayName: 'Push Docker Image'

  - stage: RemoveUnusedDockerImage
    jobs:
      - job: RemoveUnusedDockerImage
        steps:
          - script: |
              docker rmi $(registry):$(imageTag)
              docker rmi $(registry):$(imageTag)-old || true  # Ignore if image does not exist
            displayName: 'Remove Unused Docker Image'

  - stage: KubernetesDeploy
    jobs:
      - job: KubernetesDeploy
        pool:
          name: 'aks-pool'
        steps:
          - script: |
              az aks get-credentials --resource-group aks-demo-rg --name aks-demo-cluster
              cd $(Build.SourcesDirectory)/helm/vprofilecharts/templates/
              helm upgrade --install --force vprofile-stack helm/vprofilecharts --set appimage=$(registry):$(imageTag) --namespace prod
            displayName: 'Deploy to Kubernetes with kubectl'
